# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='machine',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(height_field='height', null=True, upload_to='', width_field='width'),
        ),
        migrations.AddField(
            model_name='machine',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
