# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171129_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
