# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171129_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
