# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_highscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('second', models.CharField(max_length=50)),
                ('third', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='HighScores',
        ),
    ]
