# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180222_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='machine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
