# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_highscore_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oldie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
            ],
        ),
    ]
