# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_oldie'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldiePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
            ],
        ),
        migrations.RemoveField(
            model_name='oldie',
            name='height',
        ),
        migrations.RemoveField(
            model_name='oldie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='oldie',
            name='width',
        ),
        migrations.AddField(
            model_name='oldiepic',
            name='oldie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Oldie'),
        ),
    ]
